# Generated by Django 3.2.8 on 2021-10-30 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargobot_mailing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_from', models.TextField()),
                ('city_to', models.TextField()),
                ('description', models.TextField()),
                ('cargo_weight', models.FloatField()),
                ('cargo_volume', models.FloatField()),
                ('box_amount', models.PositiveIntegerField()),
                ('transport', models.CharField(choices=[('Авиа-доставка', 'Avia'), ('ЖД-доставка', 'Railway'), ('Морская-доставка', 'Sea'), ('Авто-доставка', 'Auto')], max_length=50)),
                ('cargo_value', models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name='companyreply',
            old_name='chat_id',
            new_name='delivery_time',
        ),
        migrations.RemoveField(
            model_name='companyreply',
            name='message_id',
        ),
        migrations.AddField(
            model_name='companyreply',
            name='comment',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='companyreply',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companyreply',
            name='reply_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargobot_mailing.customerrequest'),
        ),
        migrations.DeleteModel(
            name='CustomerMessage',
        ),
    ]
